.TH FINFAKTURA 1 "2006-10-06" "" "Invoice Manager (Norway)"

.SH NAME
finfaktura \- Create and manage invoices (Norwegian specs)

.SH SYNOPSIS
usage: finfaktura

.SH DESCRIPTION
Invoices, customers, products. Creates PDF invoices. Automatic email submission and backup. Requires python and the reportlab extension. Extra value added with the beautifulsoup and libgmail modules.

.SH AUTHOR
Håvard Dahle <havard@dahle.no>.
