.TH FINFAKTURA 1 "2006-10-06" "" "Invoice Manager (Norway)"

.SH NAME
finfaktura \- Create and manage invoices (Norwegian specs)

.SH SYNOPSIS
usage: finfaktura [-i]

.SH DESCRIPTION
Invoices, customers, products. Creates PDF invoices. Automatic email submission and backup. Requires python and the reportlab extension. Extra value added with the beautifulsoup and libgmail modules.

 -i starts in interactive, non-gui mode.

.SH AUTHOR
Håvard Dahle <havard@dahle.no>.

.SH BUGS
No! Not slimy ones, anyway: http://code.google.com/p/finfaktura/issues/list

\# This groff man page (C) 2006 Håvard Dahle, GPLv2 Licenced.
\# $Id$