Document: finfaktura
Title: Debian finfaktura Manual
Author: <insert document author here>
Abstract: This manual describes what finfaktura is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/finfaktura/finfaktura.sgml.gz

Format: postscript
Files: /usr/share/doc/finfaktura/finfaktura.ps.gz

Format: text
Files: /usr/share/doc/finfaktura/finfaktura.text.gz

Format: HTML
Index: /usr/share/doc/finfaktura/html/index.html
Files: /usr/share/doc/finfaktura/html/*.html

  
