.TH FINFAKTURA 1 "2006-10-06" "" "Invoice Manager (Norway)"

.SH NAME
finfaktura \- Create and manage invoices (Norwegian specs)

.SH SYNOPSIS
usage: finfaktura [-i] [-d] [-v] [-h]

.SH DESCRIPTION
Invoices, customers, products. Creates PDF invoices. Automatic email submission and backup.

By default, the program starts up with a Qt4 gui.

 -i starts in interactive, non-gui mode.
 -d starts in debug mode, with a lot of messages printed on the console
 -v shows the finfaktura version and exits
 -h shows some help and exits.

Requires python and some python extensions: PyQt4 (package name python-qt4) and reportlab (python-reportlab).

.SH SEE ALSO
Some docs are installed under /usr/share/doc/finfaktura. The project lives on the web at http://finfaktura.googlecode.com

.SH AUTHOR
Håvard Gulldahl <havard@gulldahl.no>.

.SH BUGS
No! Not slimy ones, anyway: http://code.google.com/p/finfaktura/issues/list

\# This groff man page (C) 2006-2008 Håvard Gulldahl, GPLv2 Licenced.
\# $Id$
